apiVersion: v1
kind: Service
metadata:
  name: apiservice-np-service
spec:
  type: NodePort
  selector:
    app: apiservice
  ports:
  - name: apiservice
    protocol: TCP
    port: 5000
    targetPort: apiservice
