apiVersion: v1
kind: Service
metadata:
  name: apiservice-service
spec:
  type: NodePort
  selector:
    app: apiservice
  ports:
    - name: apiservice
      protocol: TCP
      port: 5000
      targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiservice
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      containers:
      - name: apiservice
        image: 0103990/apiservice:latest
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:5000"
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
        ports:
          - containerPort: 5000
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"