apiVersion: apps/v1
kind: Deployment
metadata:
  name: commandservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commandservice
  template:
    metadata:
      labels:
        app: commandservice
    spec:
      containers:
      - name: commandservice
        image: 0103990/commandservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:6000"
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
        ports:
          - name: http
            containerPort: 6000

---

apiVersion: v1
kind: Service
metadata:
  name: commandservice-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: commandservice
  ports:
    - name: commandservice
      protocol: TCP
      port: 6000
      targetPort: http